### ISSUE TITLE
Both operations have to have the same base length

### ISSUE THREAD

**Issue by Pasta** [ball-hayden/Collaborate#2]
Hello there,

I followed the simple steps of the README (perfect BTW), but I keep getting this error when I reload a page containing a collaborative attribute.

Basically, the first time I load the page, it just streams the data correctly. As soon as I reload the page, it stops working and I have this error:

Could not execute command from {"command"=>"message", "identifier"=>"{\"channel\":\"DocumentChannel\",\"documentId\":\"2\"}", "data"=>"{\"operation\":[78,\"\n\"],\"attribute\":\"agenda\",\"version\":1,\"client_id\":\"cd71aa7f-dabf-4314-86da-849e8c6e28cd\",\"document_id\":\"2\",\"action\":\"operation\"}"}) [RuntimeError - Both operations have to have the same base length]: /bundle/gems/ot-0.1.1/lib/ot/text_operation.rb:446:in `transform' | /bundle/bundler/gems/Collaborate-d0e0d485259a/lib/collaborate/document_attribute.rb:82:in`block in transform_old_operation' | /bundle/bundler/gems/Collaborate-d0e0d485259a/lib/collaborate/document_attribute.rb:81:in `each' | /bundle/bundler/gems/Collaborate-d0e0d485259a/lib/collaborate/document_attribute.rb:81:in`transform_old_operation' | /bundle/bundler/gems/Collaborate-d0e0d485259a/lib/collaborate/document_attribute.rb:17:in `apply_operation'

Wondering if it happened to you before or if there is something I forgot to setup?

Bests,

**Comment by ball-hayden** [comment]
This tends to happen if the server-side copy of the attribute (i.e. the redis cached version) isn't in sync with the client side.

The error (which isn't particularly clear) is that the length of the strings before you make any changes doesn't match. (It's a bit difficult to explain, sorry!)

**Comment by Pasta** [comment]
yeah, I figured it was something in these lines, but what I can't figure out it why.

Odd behavior is that when I reload the page containing the collaborative_attribute, it gets reformated -> all the lines after the first one are indented. That would then make sense for client side text (reformated with indentations) not to match the one on the redis cache.

Are you still using your gem in production and have you seen that type of behavior?

**Comment by ball-hayden** [comment]
I am no longer using this gem - it never hit production as such :frowning_face: 
I'm happy to set aside a small amount of time to keep maintaining it
though...

I'm afraid I've no idea why the attribute would be reformatted.
What are you using client side? Are you using a textbox, or are you using a
WYSIWYG editor of some sort?

**Comment by Pasta** [comment]
yeah, simple textarea!

I might also dedicate some time to make that gem hit production, as I need that capability in my current side project.

**Comment by Pasta** [comment]
Do you think it's because the client version resets to 1 every time we reload the page, but the redis cache is not cleared?

**Comment by ball-hayden** [comment]
Hmm. That would definitely have that effect.

The cache is shared between all clients, so that can't be reset, but I'm sure that the client should be made aware of its version [here](https://github.com/ball-hayden/Collaborate/blob/master/app/channels/collaborate/collaboration_channel.rb#L44) when it connects.

In hindsight, that seems a bit backwards... the client should probably _know_ its version when it is loaded.

**Comment by Pasta** [comment]
That's what I was thinking. Should this happen when subscribing?

**Comment by ball-hayden** [comment]
Yeah. 
When `Collaborate.Cable` is connected, it should be performing `document`, which in turn should be sending over all the attributes (received [here](https://github.com/ball-hayden/Collaborate/blob/master/app/assets/javascripts/collaborate/cable.coffee#L52))

**Comment by Pasta** [comment]
But somehow this [should already happen right here](https://github.com/ball-hayden/Collaborate/blob/master/app/assets/javascripts/collaborate/attribute_cable.coffee#L12)

**Comment by Pasta** [comment]
BTW, [that line](https://github.com/ball-hayden/Collaborate/blob/master/app/assets/javascripts/collaborate/cable.coffee#L52) is actually one of the blockers of not having the version passed to the client. Any reason it exists?
